Allow overriding user and group used
voxpupuli/puppet-nomad pull request #71
Opened 2022-12-12 17:13 UTC by jonasdemoor

#### Pull Request (PR) description

This PR adds two parameters to the base class, `$user` and `$group`, so one can specify which user and group should be used to run Nomad. This would allow one to run the Nomad server with a seperate user, as per upstream's recommendation: https://developer.hashicorp.com/nomad/docs/install/production/requirements#user-permissions

I used `root` as default for both parameters to not break people's existing workflows.

#### This Pull Request (PR) fixes the following issues

Fixes #66

2022-12-12 18:10 UTC, kenyon requested changes
Could you add some testing of these parameters to https://github.com/voxpupuli/puppet-nomad/blob/master/spec/classes/init_spec.rb ?

2022-12-12 19:59 UTC, jonasdemoor commented
I amended my commit and added some tests

2022-12-12 20:00 UTC, bastelfreak commented on manifests/init.pp
> +  String $user                                   = 'root',
```suggestion
  String[1] $user                                = 'root',
```

2022-12-12 20:01 UTC, bastelfreak commented on manifests/init.pp
> +  String $group                                  = 'root',
```suggestion
  String[1] $group                               = 'root',
```

2022-12-12 20:03 UTC, bastelfreak commented
can you explain what kind of jobs you run with nomad? I am wondering if it makes sense for the next major release to switch to a nonroot default user.

2022-12-13 08:53 UTC, jonasdemoor commented
> can you explain what kind of jobs you run with nomad? I am wondering if it makes sense for the next major release to switch to a nonroot default user.

At this moment nothing yet, we're still in the experimental/setup phase :) When reading Nomad's documentation [1], I think client/worker nodes need to be run as root, while the server/scheduler nodes can be run as another user.

[1] https://developer.hashicorp.com/nomad/docs/install/production/requirements#user-permissions

2022-12-13 09:38 UTC, merged

2023-01-05 10:40 UTC, linuxmail commented
It works quite well , if using for example Docker and adding the nomad user to the docker group. It fails for sure, if you use things like Consul "connect", as it requies iptables etc. pp.